# UP

CREATE TABLE IF NOT EXISTS tasas (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  valor DECIMAL(8,2) NOT NULL,
  fecha TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE ventas ADD COLUMN idTasa BIGINT REFERENCES tasas(id);
ALTER TABLE abonos ADD COLUMN  idTasa BIGINT REFERENCES tasas(id);
ALTER TABLE cuentas_apartados ADD COLUMN  idTasa BIGINT REFERENCES tasas(id);

ALTER TABLE productos ADD COLUMN precioVenta5 DECIMAL(8,2) AFTER precioVenta4; 
ALTER TABLE productos ADD COLUMN precioVenta6 DECIMAL(8,2) AFTER precioVenta5; 
ALTER TABLE productos ADD COLUMN precioVenta7 DECIMAL(8,2) AFTER precioVenta6; 

# DOWN

DROP TABLE tasas;

ALTER TABLE ventas DROP COLUMN idTasa;
ALTER TABLE abonos DROP COLUMN idTasa;
ALTER TABLE cuentas_apartados DROP COLUMN idTasa;

ALTER TABLE productos DROP COLUMN precioVenta5; 
ALTER TABLE productos DROP COLUMN precioVenta6; 
ALTER TABLE productos DROP COLUMN precioVenta7; 